language: scala

script: sbt ++$TRAVIS_SCALA_VERSION "test"
after_script:
  - sbt coveralls

scala:
- 2.11.7

jdk:
- oraclejdk8

env:
  global:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"